### ISSUE TITLE
System.InvalidCastException on build

### ISSUE THREAD

**Issue by kubala156** [LarsSkovslund/NuGet.Package.Builder#28]
Hi, i getting `System.InvalidCastException: Unable to cast object of type 'System.String' to type 'NuGet.Frameworks.NuGetFramework'` on my project build.

I have your library from NuGet, version 1.0.12.
When i clone project from repository and replace tools/nuget.exe with latest stable from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe everything works fine, so you may update toolset and push new NuGet package.

```
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error : System.InvalidCastException: Unable to cast object of type 'System.String' to type 'NuGet.Frameworks.NuGetFramework'.
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.ProjectManagement.NuGetProject.GetMetadata[T](String key)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.ProjectManagement.PackagesConfigNuGetProject..ctor(String folderPath, Dictionary`2 metadata)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at CallSite.Target(Closure , CallSite , Type , Object , Dictionary`2 )
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.ProjectFactory.AddDependencies(Dictionary`2 packagesAndDependencies)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action`1 action, Object alreadyAppliedProjects)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action`1 action, Object alreadyAppliedProjects)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.ProjectFactory.RecursivelyApply(Action`1 action)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.ProjectFactory.ProcessDependencies(PackageBuilder builder)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.PackCommand.ExecuteCommand()
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.Command.ExecuteCommandAsync()
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.Command.Execute()
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error :    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
2>D:\project\packages\NuGet.Package.Builder.1.0.12\build\NuGet.Package.Builder.targets(30,3): error MSB3073: The command ""D:\project\packages\NuGet.Package.Builder.1.0.12\tools\NuGet.Package.Builder.exe" --path "D:\project\packages\NuGet.Package.Builder.1.0.12\tools" -r "THE_PROJECT" -t "THE_PROJECT" -e .csproj -c "Release" -p "Configuration=Release;Platform=AnyCPU" -o "D:\project\THE_PROJECT\bin\Release" -w "D:\project\THE_PROJECT"     " exited with code -1.
```

**Comment by LarsSkovslund** [comment]
I have consider the project to be dead as `dotnet` now have native support for this, but I'll gladly accept a PR and publish a new version.

**Comment by LarsSkovslund** [comment]
[Version 1.0.13](https://www.nuget.org/packages/NuGet.Package.Builder/1.0.13) is now available on nuget.
Thanks for contributing @kubala156  👍 .
