### ISSUE TITLE
Builder not waiting long enough for nuget to finish building nupkg

### ISSUE THREAD

**Issue by ahazelwood** [LarsSkovslund/NuGet.Package.Builder#3]
I have a build process which takes a long time to complete building the nupkg (> 20 seconds).  

This causes the nuget push process to throw an error because the nupkg is still being held open by the build process.  Please allow for the builder to complete before moving forward, or allow a configurable timeout for each process to complete in Program.cs.

Thanks.  

```
D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release>"D:\projects\branches\3.22\packages\NuGet.Package.Builder.1.0.7\tools\NuGet.Package.Builder.exe" --path "D:\projects\branches\3.
22\packages\NuGet.Package.Builder.1.0.7\tools" -t "DocumentHost" -e .csproj -c "Release" -p "Configuration=Release;Platform=AnyCPU" -o "D:\projects\branches\3.22\processing\documents\DocumentHost\bin\
Release" -w "D:\projects\branches\3.22\processing\documents\DocumentHost"
D:\projects\branches\3.22\packages\NuGet.Package.Builder.1.0.7\tools\NuGet.exe pack "D:\projects\branches\3.22\processing\documents\DocumentHost\DocumentHost.csproj"  -NoDefaultExcludes -Verbosity Det
ailed -Properties "OutDir=D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release;Configuration=Release;Platform=AnyCPU" -NonInteractive -OutputDirectory "D:\projects\branches\3.22\pro
cessing\documents\DocumentHost\bin\Release" -basepath "D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release" -IncludeReferencedProjects
Attempting to build package from 'DocumentHost.csproj'.
Packing files from 'D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release'.
Using 'DocumentHost.nuspec' for metadata.
Add file 'D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release\DocumentHost.exe' to package as 'lib\net46\DocumentHost.exe'
Add file 'D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release\CI.Models.dll' to package as 'lib\net46\CI.Models.dll'
Add file 'D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release\CI.dll' to package as 'lib\net46\CI.dll'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Czech.txt' to package as 'content\Text\Language\Dictionary\Czech.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Danish.txt' to package as 'content\Text\Language\Dictionary\Danish.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\English.txt' to package as 'content\Text\Language\Dictionary\English.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\French.txt' to package as 'content\Text\Language\Dictionary\French.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\German.txt' to package as 'content\Text\Language\Dictionary\German.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Greek.txt' to package as 'content\Text\Language\Dictionary\Greek.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Hungarian.txt' to package as 'content\Text\Language\Dictionary\Hungarian.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Italian.txt' to package as 'content\Text\Language\Dictionary\Italian.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Norwegian.txt' to package as 'content\Text\Language\Dictionary\Norwegian.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Polish.txt' to package as 'content\Text\Language\Dictionary\Polish.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Portuguese.txt' to package as 'content\Text\Language\Dictionary\Portuguese.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Romanian.txt' to package as 'content\Text\Language\Dictionary\Romanian.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Russian.txt' to package as 'content\Text\Language\Dictionary\Russian.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Spanish.txt' to package as 'content\Text\Language\Dictionary\Spanish.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Swedish.txt' to package as 'content\Text\Language\Dictionary\Swedish.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Arabic.txt' to package as 'content\Text\Language\Dictionary\Arabic.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\Dictionary\Vietnamese.txt' to package as 'content\Text\Language\Dictionary\Vietnamese.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Language\include\CommonWords.txt' to package as 'content\Text\Language\include\CommonWords.txt'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\bg.xml' to package as 'content\Text\Summarize\dics\bg.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\ca.xml' to package as 'content\Text\Summarize\dics\ca.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\cs.xml' to package as 'content\Text\Summarize\dics\cs.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\cy.xml' to package as 'content\Text\Summarize\dics\cy.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\da.xml' to package as 'content\Text\Summarize\dics\da.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\de.xml' to package as 'content\Text\Summarize\dics\de.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\el.xml' to package as 'content\Text\Summarize\dics\el.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\en.xml' to package as 'content\Text\Summarize\dics\en.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\eo.xml' to package as 'content\Text\Summarize\dics\eo.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\es.xml' to package as 'content\Text\Summarize\dics\es.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\et.xml' to package as 'content\Text\Summarize\dics\et.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\eu.xml' to package as 'content\Text\Summarize\dics\eu.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\fi.xml' to package as 'content\Text\Summarize\dics\fi.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\fr.xml' to package as 'content\Text\Summarize\dics\fr.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\ga.xml' to package as 'content\Text\Summarize\dics\ga.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\gl.xml' to package as 'content\Text\Summarize\dics\gl.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\he.xml' to package as 'content\Text\Summarize\dics\he.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\hu.xml' to package as 'content\Text\Summarize\dics\hu.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\ia.xml' to package as 'content\Text\Summarize\dics\ia.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\id.xml' to package as 'content\Text\Summarize\dics\id.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\is.xml' to package as 'content\Text\Summarize\dics\is.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\it.xml' to package as 'content\Text\Summarize\dics\it.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\lv.xml' to package as 'content\Text\Summarize\dics\lv.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\mi.xml' to package as 'content\Text\Summarize\dics\mi.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\ms.xml' to package as 'content\Text\Summarize\dics\ms.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\mt.xml' to package as 'content\Text\Summarize\dics\mt.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\nl.xml' to package as 'content\Text\Summarize\dics\nl.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\nn.xml' to package as 'content\Text\Summarize\dics\nn.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\pl.xml' to package as 'content\Text\Summarize\dics\pl.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\pt.xml' to package as 'content\Text\Summarize\dics\pt.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\ro.xml' to package as 'content\Text\Summarize\dics\ro.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\ru.xml' to package as 'content\Text\Summarize\dics\ru.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\sv.xml' to package as 'content\Text\Summarize\dics\sv.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\tl.xml' to package as 'content\Text\Summarize\dics\tl.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\tr.xml' to package as 'content\Text\Summarize\dics\tr.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\uk.xml' to package as 'content\Text\Summarize\dics\uk.xml'
Add file 'D:\projects\branches\3.22\library\CI\Text\Summarize\dics\yi.xml' to package as 'content\Text\Summarize\dics\yi.xml'
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
D:\projects\branches\3.22\packages\NuGet.Package.Builder.1.0.7\tools\NuGet.exe push "D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release\DocumentHost.*.nupkg" radar -s http://deplo
y.ciradar.com/  -Timeout 300 -Verbosity Detailed -NonInteractive
System.IO.IOException: The process cannot access the file 'D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release\DocumentHost.1.0.0.0.nupkg' because it is being used by another proce
ss.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, St
ring msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalFileSystem.OpenFile(String path)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.OptimizedZipPackage..ctor(String fullPackagePath)
   at NuGet.Commands.PushCommand.PushPackageCore(String source, String apiKey, PackageServer packageServer, String packageToPush, TimeSpan timeout)
   at NuGet.Commands.PushCommand.PushPackage(String packagePath, String source, String apiKey, TimeSpan timeout)
   at NuGet.Commands.PushCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)

D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release>"D:\projects\branches\3.22\packages\NuGet.Package.Builder.1.0.7\tools\NuGet.Package.Builder.exe" --path "D:\projects\branches\3.
Id: DocumentHostt.Package.Builder.1.0.7\tools" -t "DocumentHost" -e .csproj -c "Release" -p "Configuration=Release;Platform=AnyCPU" -o "D:\projects\branches\3.22\processing\documents\DocumentHost\bin\
Version: 1.0.0.0projects\branches\3.22\processing\documents\DocumentHost"
Authors: CI Radar
Description: Runtime for the Document Processing Framework
Tags: ANY
Dependencies: NLog.Config (≥ 4.1.0), Newtonsoft.Json (≥ 7.0.1), SqlFu (≥ 2.3.8), CsQuery (≥ 1.3.4), CS-Script (≥ 3.9.10.0), EnterpriseLibrary.Data (≥ 6.0.1304.0), HtmlAgilityPack (≥ 1.4.9), Lucene.Net
.Contrib (≥ 3.0.3), mongocsharpdriver (≥ 2.0.1), p3-sharpcompress (≥ 0.10.5.2)

Added file 'content\Text\Language\Dictionary\Arabic.txt'.
Added file 'content\Text\Language\Dictionary\Czech.txt'.
Added file 'content\Text\Language\Dictionary\Danish.txt'.
Added file 'content\Text\Language\Dictionary\English.txt'.
Added file 'content\Text\Language\Dictionary\French.txt'.
Added file 'content\Text\Language\Dictionary\German.txt'.
Added file 'content\Text\Language\Dictionary\Greek.txt'.
Added file 'content\Text\Language\Dictionary\Hungarian.txt'.
Added file 'content\Text\Language\Dictionary\Italian.txt'.
Added file 'content\Text\Language\Dictionary\Norwegian.txt'.
Added file 'content\Text\Language\Dictionary\Polish.txt'.
Added file 'content\Text\Language\Dictionary\Portuguese.txt'.
Added file 'content\Text\Language\Dictionary\Romanian.txt'.
Added file 'content\Text\Language\Dictionary\Russian.txt'.
Added file 'content\Text\Language\Dictionary\Spanish.txt'.
Added file 'content\Text\Language\Dictionary\Swedish.txt'.
Added file 'content\Text\Language\Dictionary\Vietnamese.txt'.
Added file 'content\Text\Language\include\CommonWords.txt'.
Added file 'content\Text\Summarize\dics\bg.xml'.
Added file 'content\Text\Summarize\dics\ca.xml'.
Added file 'content\Text\Summarize\dics\cs.xml'.
Added file 'content\Text\Summarize\dics\cy.xml'.
Added file 'content\Text\Summarize\dics\da.xml'.
Added file 'content\Text\Summarize\dics\de.xml'.
Added file 'content\Text\Summarize\dics\el.xml'.
Added file 'content\Text\Summarize\dics\en.xml'.
Added file 'content\Text\Summarize\dics\eo.xml'.
Added file 'content\Text\Summarize\dics\es.xml'.
Added file 'content\Text\Summarize\dics\et.xml'.
Added file 'content\Text\Summarize\dics\eu.xml'.
Added file 'content\Text\Summarize\dics\fi.xml'.
Added file 'content\Text\Summarize\dics\fr.xml'.
Added file 'content\Text\Summarize\dics\ga.xml'.
Added file 'content\Text\Summarize\dics\gl.xml'.
Added file 'content\Text\Summarize\dics\he.xml'.
Added file 'content\Text\Summarize\dics\hu.xml'.
Added file 'content\Text\Summarize\dics\ia.xml'.
Added file 'content\Text\Summarize\dics\id.xml'.
Added file 'content\Text\Summarize\dics\is.xml'.
Added file 'content\Text\Summarize\dics\it.xml'.
Added file 'content\Text\Summarize\dics\lv.xml'.
Added file 'content\Text\Summarize\dics\mi.xml'.
Added file 'content\Text\Summarize\dics\ms.xml'.
Added file 'content\Text\Summarize\dics\mt.xml'.
Added file 'content\Text\Summarize\dics\nl.xml'.
Added file 'content\Text\Summarize\dics\nn.xml'.
Added file 'content\Text\Summarize\dics\pl.xml'.
Added file 'content\Text\Summarize\dics\pt.xml'.
Added file 'content\Text\Summarize\dics\ro.xml'.
Added file 'content\Text\Summarize\dics\ru.xml'.
Added file 'content\Text\Summarize\dics\sv.xml'.
Added file 'content\Text\Summarize\dics\tl.xml'.
Added file 'content\Text\Summarize\dics\tr.xml'.
Added file 'content\Text\Summarize\dics\uk.xml'.
Added file 'content\Text\Summarize\dics\yi.xml'.
Added file 'lib\net46\CI.dll'.
Added file 'lib\net46\CI.Models.dll'.
Added file 'lib\net46\DocumentHost.exe'.

Successfully created package 'D:\projects\branches\3.22\processing\documents\DocumentHost\bin\Release\DocumentHost.1.0.0.0.nupkg'.
```

**Comment by LarsSkovslund** [comment]
Hi ahazelwood,

Nice spotted, I've removed the timeout restriction all together as there was no point in keeping it.
Release 1.0.8 is now available on NuGet.

Cheers
  Lars

**Comment by ahazelwood** [comment]
Great.  Fixed the issue.
